on:
  push:
     branches:
       - main
permissions:
  contents: write
jobs:
  update-readme:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run a script
        run: |
          chmod +x ./docs/create_preview.sh
          ./docs/create_preview.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
